[toolchain]

[features]
resolution = []
skip-lint = []

[programs.localnet]
truedeal = "TrDeaL1111111111111111111111111111111111111"

[programs.devnet]
truedeal = "TrDeaL1111111111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
