[workspace]
resolver = "2"
members = [
    "programs/*"
]


[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[patch.crates-io]
getrandom = { git = "https://github.com/rust-random/getrandom", tag = "v0.2.10" }
hashbrown = { path = "vendor/hashbrown" }
block-buffer = { path = "vendor/block-buffer-0.10.4" }
syn = { path = "vendor/syn" }









