[package]
name = "truedeal"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "truedeal"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
solana-program = "=1.17.17"
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
spl-token = "=4.0.0"
spl-token-2022 = "=0.9.0"
spl-memo = "=4.0.0"
spl-associated-token-account = "=1.1.3"
toml_datetime = "=0.6.5"
bitflags = "=2.4.0"













