[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/RustCrypto/traits.git?tag=digest-v0.10.7"]
git = "https://github.com/RustCrypto/traits.git"
tag = "digest-v0.10.7"
replace-with = "vendored-sources"

[source."git+https://github.com/dtolnay/proc-macro2.git?tag=1.0.86"]
git = "https://github.com/dtolnay/proc-macro2.git"
tag = "1.0.86"
replace-with = "vendored-sources"

[source."git+https://github.com/rust-random/getrandom?tag=v0.2.10"]
git = "https://github.com/rust-random/getrandom"
tag = "v0.2.10"
replace-with = "vendored-sources"

[source."git+https://github.com/serde-rs/json.git?tag=v1.0.128"]
git = "https://github.com/serde-rs/json.git"
tag = "v1.0.128"
replace-with = "vendored-sources"

[source."git+https://github.com/toml-rs/toml?tag=toml_datetime-v0.6.3"]
git = "https://github.com/toml-rs/toml"
tag = "toml_datetime-v0.6.3"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor/"
